homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create/', views.create_schedule, name='create_schedule'),
    path('schedule/delete', views.delete_schedule, name='delete_schedule'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='home')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):

    # Fields
    title = models.CharField(max_length=50)
    location = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    category = models.CharField(max_length=100) 

    def __str__(self):
        return self.title

homepage/forms.py
from django import forms
from . import models

class CreateSchedule(forms.ModelForm):
    class Meta:
        model = models.Schedule
        fields = ['title','location','date','time','category']

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms


# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

def contact(request):
    return render(request, 'contact.html')

def gallery(request):
    return render(request, 'gallery.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html',{'schedules':schedules})

def create_schedule(request):
    if request.method == 'POST':
        form = forms.CreateSchedule(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:schedule')
    else:
        form = forms.CreateSchedule()
    return render(request, 'create_schedule.html',{'form': form})

def delete_schedule(request):
    if request.method == "POST":
        id = request.POST['id']
        Schedule.objects.get(id=id).delete()
    return redirect('homepage:schedule')

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style=""><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta n="" ame="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <script src="{% static 'script/script.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>{% block title %}WELCOME! | Farizio Kautsar Heruzy{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-custom justify-content-center fixed-top" style="box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.15);">
        <ul class="navbar-nav">
            <li class="nav-item" style = "margin-right: 4vw">
            <a class="nav-link" href="{% url 'homepage:gallery' %}">GALLERY</a>
            </li>
            <li class="nav-item" >
            <a class="nav-link" href="{% url 'homepage:homepage' %}">HOME</a>
            </li>
            <li class="nav-item" style = "margin-left: 4vw">
            <a class="nav-link" href="{% url 'homepage:contact' %}">CONTACT ME</a>
            </li>
        </ul>
    </nav>


{% block body %}
{% endblock %}

</body>

homepage/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
CONTACT | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
<div class="page">
    <div class = "sidebyside">
        <div class = "head_left">          
            <div class = "page_phone">
                <div class = "line" style="margin-bottom: 2vw;">
                </div>
                <div>
                    <a id = "like">Like</a>
                    <a class = "button" href="{% url 'homepage:gallery' %}" style = "color: black">my stuffs?</a>
                </div>
                <div style = "height: 4vw">

                    </div>
                <p class = "findme">
                    You can find me on:
                </p>
                <div style = "height: 2vw">

                    </div>
                <div class = "row_class">
                    <a  href="https://api.whatsapp.com/send?phone=6281282100255">
                        <img class = "contact_icons" src="{% static 'images/contact_icons/whatsapp.svg' %}"></img>
                    </a>
                    <a  href="https://www.instagram.com/ziokautsar/">
                        <img class = "contact_icons" src="{% static 'images/contact_icons/instagram.svg' %}"></img>
                    </a>
                    <a  href="https://www.linkedin.com/in/farizio-kautsar-655844126/">
                        <img class = "contact_icons" src="{% static 'images/contact_icons/linkedin.svg' %}"></img>
                    </a>
                    <a  href="https://twitter.com/farizio_kautsar">
                        <img class = "contact_icons" src="{% static 'images/contact_icons/twitter.svg' %}"></img>
                    </a>
                </div>
                <div style = "height: 4vw">

                    </div>
                <div class = "row_class">
                    <img src = "{% static 'images/icons/email.svg' %}" class = "contact_emailphone">
                    </img>
                    <p class = "contact_emailphone_text"">
                        kheruzy@gmail.com
                    </p>
                    <div style = "width: 45px"></div>
                    <img src = "{% static 'images/icons/phone.svg' %}" class = "contact_emailphone">
                    </img>
                    <p class = "contact_emailphone_text"">
                        +62 812 8210 0255
                    </p>
                </div>
                <div style = "height: 60px"></div>
                <div style = "height: 4vw"></div>
                <a class = "button" href="{% url 'homepage:schedule' %}">
                    SEE MY SCHEDULE
                </a>
                <div style = "height: 4vw"></div>
                <div class = "line">
                </div>
                <p id = "excited">
                    I'm excited to be a part of your next big project
                </p>
                <div style = "height: 4vw"></div>
                <a class = "button" href="{% url 'homepage:homepage' %}">
                    BACK HOME
                </a>
                <div style = "height: 20vw"></div>
            </div>
        </div>
        <div class = "head_right" id="contact">
            <img src="{% static 'images/contact_side.jpg' %}" class="pic_phone"></img>
        </div>
    </div>
<!-- <div class = "whatido_background"> -->
    
</div>
<!-- <div class = "programs_background"> -->
    
</div>
<!-- <div class = "languages_background"> -->
    
</div>
</div>
{% endblock %}

homepage/templates/create_schedule.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
CREATE SCHEDULE | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
<div class="page">
    <div class="line" style="margin-bottom:0vw; background-color: #3293ED"></div>
    <h1 style="color: #3293ED">Create Schedule</h1>
    <div style="height: 2vw"></div>
    <form class="forms" action="{% url 'homepage:create_schedule' %}" method="POST">
        {% csrf_token %}
        <div class = "container">
            <div class="col">
                <div class = "row align-items-end">
                    <div class="col">
                        <h1>Title</h1>
                        <p>How would you refer this schedule?</p>
                        {{ form.title }}
                    </div>
                    <div class="col">
                        <h1>Date</h1>
                        <p>When will this be held (format: yyyy-mm-dd)</p>
                        {{ form.date }}
                    </div>
                </div>
                <div style="height: 2vw"></div>
                <div class = "row align-items-end">
                    <div class="col">
                        <h1>Category</h1>
                        <p>What is this schedule for? (Ex: Meeting, Busy, etc)</p>
                        {{ form.category }}
                    </div>
                    <div class="col">
                        <h1>Time</h1>
                        <p>At what time? (format: hh:mm:ss)</p>
                        {{ form.time }}
                    </div>
                </div>
                <div style="height: 2vw"></div>
                <div class = "row align-items-end">
                    <div class="col">
                        <h1>Location</h1>
                        <p>Where will this schedule be held?</p>
                        {{ form.location }}
                    </div>
                    <div class="col">
                        <input class="button" type="submit" value="Add Schedule">
                    </div>
                </div>
            </div>
        </div>
        <div style="height: 2vw"></div>
    </form>
</div>
{% endblock %}

homepage/templates/gallery.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
GALLERY | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
    <div class="page">        
        <p class = "oneline">
            Find what you like
        </p>
        <div class = "line">
            </div>
        <p style = "font-size: calc(0.1rem + 0.5vw); color:#AEAEAE">
                *DUMMY ARTS*
            </p>
        <div style = "height: 60px">

            </div>
        <div class = "column_class">
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=815&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1526304760382-3591d3840148?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1484589065579-248aad0d8b13?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=396&q=80" style="width: 100%;"></img>
                </a>
            </div>
            <div style = "height: 20px">
            </div>
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1551913902-c92207136625?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1554188248-986adbb73be4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1549490349-8643362247b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" style="width: 100%;"></img>
                </a>
            </div>
            <div style = "height: 20px">
                </div>
            <div class = "row_class">
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1549887534-1541e9326642?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=401&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame">
                    <img src = "https://images.unsplash.com/photo-1482160549825-59d1b23cb208?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" style="width: 100%;"></img>
                </a>
                <div style = "width: 60px">
                </div>
                <a class = "artwork_frame" >
                    <img src = "https://images.unsplash.com/photo-1493210977798-4f655ac200a9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=562&q=80" style="width: 100%;"></img>
                </a>
            </div>
        </div>
        <div style = "height: 150px">

        </div>
        <div style="text-align: center; font-weight: 700;">
            <p class ="oneline">Like what you see?</p>
            <div style = "height: 60px">

                </div>
            <div class="line">

                </div>
        </div>
        <div style = "height: 60px">

        </div>
        <!-- BUTTON CONTACT ME -->
        <div style="text-align: center; ">
            <a class = "button" href="{% url 'home:contact' %}">
                RING ME
            </a>
        </div>
        <div style = "height: 300px">

        </div>
    </div>
{% endblock %}

homepage/templates/schedule.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
SCHEDULE | Farizio Kautsar Heruzy
{% endblock %}
{% block body %}
<div class="page">
    <div stlye = "display:flex; align-items: center; justify-content:center;">
        <a class = "button" href="{% url 'homepage:create_schedule' %}">
            CREATE NEW SCHEDULE
        </a>
    </div>
    <div style="height: 2vw"></div>
    <div class = "schedules">
        {% for schedule in schedules %}
            <div class = "schedule">
                <h1>{{schedule.title}}</h1>
                <h2>{{schedule.category}}</h2>
                <div class="container">
                    <div class="row">
                        <div class = "col-0">
                            <img src = "{% static 'images/icons/location.svg' %}"
                            class = "info_icon">
                            </img>
                        </div>
                        <div class = "col">
                            <h3>{{schedule.location}}</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class = "col-0">
                            <img src = "{% static 'images/icons/calendar.svg' %}"
                            class = "info_icon">
                            </img>
                        </div>
                        <div class = "col">
                            <h3>{{schedule.date}}</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class = "col-0">
                            <img src = "{% static 'images/icons/clock.svg' %}"
                            class = "info_icon">
                            </img>
                        </div>
                        <div class = "col">
                            <h3>{{schedule.time}}</h3>
                        </div>
                    </div>
                    <div class="row align-items-end">
                        <form action="delete" method="POST" >
                            {% csrf_token %}
                            <input type="hidden" value="{{ schedule.id }}" name="id" />
                            <input class="button" style = "font-size: 1vw;line-height: 2vw" type="submit" value="Delete" />
                        </form>
                    </div>
                </div>
                
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}